### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by centerepic** [typicalcold/roblox-external-esp-OBS-hide#2]
Why not write this in C++ or some other fast language? It seems strange to use python for this as it's a lot more annoying to use the windows APIs through it and it's just overall pretty slow for an application like this.

Using imgui to make an external overlay in C++ is pretty easy I would recommend switching to that if performance ever becomes an issue.

Cool project though!

**Comment by typicalcold** [comment]
I wrote it in python because it is a fairly simple language to code in. I also wanted to learn some python because I have very little experience in it. C++ would be better, but it's too complicated for me. More people would be able to customize and modify it because I chose python
